name: nc_flutter_google_maps
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  states_rebuilder: ^6.3.0
  #* google maps package
  google_maps_flutter: ^2.5.3 # check for the latest version
  #* google maps package for web
  google_maps_flutter_web: ^0.5.4+3 # check for the latest version
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
