// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhVvzBstzRriEXMY6O4uFm_CXlwjXW11c',
    appId: '1:147051352354:web:018d792fb32caccc82d57b',
    messagingSenderId: '147051352354',
    projectId: 'nc-flutter-gmaps',
    authDomain: 'nc-flutter-gmaps.firebaseapp.com',
    storageBucket: 'nc-flutter-gmaps.appspot.com',
    measurementId: 'G-KMTPJ07ZCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkWaNL-BWuCsXrB4H1acnfDHWcxC8Q7hk',
    appId: '1:147051352354:android:03034abc1d3121b482d57b',
    messagingSenderId: '147051352354',
    projectId: 'nc-flutter-gmaps',
    storageBucket: 'nc-flutter-gmaps.appspot.com',
  );
}
